{{- if .Values.grafana.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ include "beacon.namespace" . }}
  labels:
    {{- include "beacon.labels" . | nindent 4 }}
    {{- include "beacon.componentLabels" "grafana" | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:{{ .Values.prometheus.service.port }}
        isDefault: true
        editable: true

      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki:{{ .Values.loki.service.port }}
        editable: true
        jsonData:
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: "trace_id=(\\w+)"
              name: TraceID
              url: "$${__value.raw}"

      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://tempo:{{ .Values.tempo.service.port }}
        editable: true
        jsonData:
          tracesToLogsV2:
            datasourceUid: 'loki'
            spanStartTimeShift: '-1h'
            spanEndTimeShift: '1h'
            filterByTraceID: true
            filterBySpanID: false
{{- end }}
