{{- if .Values.grafana.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  namespace: {{ include "beacon.namespace" . }}
  labels:
    {{- include "beacon.labels" . | nindent 4 }}
    {{- include "beacon.componentLabels" "grafana" | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.grafana.storage.storageClassName }}
  storageClassName: {{ .Values.grafana.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.grafana.storage.size }}
{{- end }}
